export const soft = [
  {
    1: 'bezpośredni',
    2: 'bezpośredniego',
    3: 'bezpośredniemu',
    4: 'bezpośrednim',
    5: 'bezpośrednie',
    6: 'bezpośrednia',
    7: 'bezpośredniej',
    8: 'bezpośrednią',
    9: 'bezpośredni',
    10: 'bezpośrednich',
    11: 'bezpośrednimi',
  },
  {
    1: 'ostatni',
    2: 'ostatniego',
    3: 'ostatniemu',
    4: 'ostatnim',
    5: 'ostatnie',
    6: 'ostatnia',
    7: 'ostatniej',
    8: 'ostatnią',
    9: 'ostatni',
    10: 'ostatnich',
    11: 'ostatnimi',
  },
  {
    1: 'tani',
    2: 'taniego',
    3: 'taniemu',
    4: 'tanim',
    5: 'tanie',
    6: 'tania',
    7: 'taniej',
    8: 'tanią',
    9: 'tani',
    10: 'tanich',
    11: 'tanimi',
  },
  {
    1: 'głupi',
    2: 'głupiego',
    3: 'głupiemu',
    4: 'głupim',
    5: 'głupie',
    6: 'głupia',
    7: 'głupiej',
    8: 'głupią',
    9: 'głupi',
    10: 'głupich',
    11: 'głupimi',
  },
  {
    1: 'trzeci',
    2: 'trzeciego',
    3: 'trzeciemu',
    4: 'trzecim',
    5: 'trzecie',
    6: 'trzecia',
    7: 'trzeciej',
    8: 'trzecią',
    9: 'trzeci',
    10: 'trzecich',
    11: 'trzecimi',
  },
  {
    1: 'gęsi',
    2: 'gęsiego',
    3: 'gęsiemu',
    4: 'gęsim',
    5: 'gęsie',
    6: 'gęsia',
    7: 'gęsiej',
    8: 'gęsią',
    9: 'gęsi',
    10: 'gęsich',
    11: 'gęsimi',
  },
  {
    1: 'owadzi',
    2: 'owadziego',
    3: 'owadziemu',
    4: 'owadzim',
    5: 'owadzie',
    6: 'owadzia',
    7: 'owadziej',
    8: 'owadzią',
    9: 'owadzi',
    10: 'owadzich',
    11: 'owadzimi',
  },
  {
    1: 'anieli',
    2: 'anielego',
    3: 'anielemu',
    4: 'anielim',
    5: 'aniele',
    6: 'aniela',
    7: 'anielej',
    8: 'anielą',
    9: 'anieli',
    10: 'anielich',
    11: 'anielimi',
  },
]

export const hardened = [
  {
    1: 'badawczy',
    2: 'badawczego',
    3: 'badawczemu',
    4: 'badawczym',
    5: 'badawcze',
    6: 'badawcza',
    7: 'badawczej',
    8: 'badawczą',
    9: 'badawczy',
    10: 'badawczych',
    11: 'badawczymi',
  },
  {
    1: 'będący',
    2: 'będącego',
    3: 'będącemu',
    4: 'będącym',
    5: 'będące',
    6: 'będąca',
    7: 'będącej',
    8: 'będącą',
    9: 'będący',
    10: 'będących',
    11: 'będącymi',
  },
  {
    1: 'boży',
    2: 'bożego',
    3: 'bożemu',
    4: 'bożym',
    5: 'boże',
    6: 'boża',
    7: 'bożej',
    8: 'bożą',
    9: 'boży',
    10: 'bożych',
    11: 'bożymi',
  },
  {
    1: 'cudzy',
    2: 'cudzego',
    3: 'cudzemu',
    4: 'cudzym',
    5: 'cudze',
    6: 'cudza',
    7: 'cudzej',
    8: 'cudzą',
    9: 'cudzy',
    10: 'cudzych',
    11: 'cudzymi',
  },
  {
    1: 'bliższy',
    2: 'bliższego',
    3: 'bliższemu',
    4: 'bliższym',
    5: 'bliższe',
    6: 'bliższa',
    7: 'bliższej',
    8: 'bliższą',
    9: 'bliżsi',
    10: 'bliższych',
    11: 'bliższymi',
  },
  {
    1: 'cichszy',
    2: 'cichszego',
    3: 'cichszemu',
    4: 'cichszym',
    5: 'cichsze',
    6: 'cichsza',
    7: 'cichszej',
    8: 'cichszą',
    9: 'cichsi',
    10: 'cichszych',
    11: 'cichszymi',
  },
  {
    1: 'dalszy',
    2: 'dalszego',
    3: 'dalszemu',
    4: 'dalszym',
    5: 'dalsze',
    6: 'dalsza',
    7: 'dalszej',
    8: 'dalszą',
    9: 'dalsi',
    10: 'dalszych',
    11: 'dalszymi',
  },
  {
    // Wyjątek
    1: 'duży',
    2: 'dużego',
    3: 'dużemu',
    4: 'dużym',
    5: 'duże',
    6: 'duża',
    7: 'dużej',
    8: 'dużą',
    9: 'duzi',
    10: 'dużych',
    11: 'dużymi',
  },
]

export const back = [
  {
    1: 'długi',
    2: 'długiego',
    3: 'długiemu',
    4: 'długim',
    5: 'długie',
    6: 'długa',
    7: 'długiej',
    8: 'długą',
    9: 'dłudzy',
    10: 'długich',
    11: 'długimi',
  },
  {
    1: 'drogi',
    2: 'drogiego',
    3: 'drogiemu',
    4: 'drogim',
    5: 'drogie',
    6: 'droga',
    7: 'drogiej',
    8: 'drogą',
    9: 'drodzy',
    10: 'drogich',
    11: 'drogimi',
  },
  {
    1: 'ubogi',
    2: 'ubogiego',
    3: 'ubogiemu',
    4: 'ubogim',
    5: 'ubogie',
    6: 'uboga',
    7: 'ubogiej',
    8: 'ubogą',
    9: 'ubodzy',
    10: 'ubogich',
    11: 'ubogimi',
  },
  {
    1: 'angielski',
    2: 'angielskiego',
    3: 'angielskiemu',
    4: 'angielskim',
    5: 'angielskie',
    6: 'angielska',
    7: 'angielskiej',
    8: 'angielską',
    9: 'angielscy',
    10: 'angielskich',
    11: 'angielskimi',
  },
  {
    1: 'bliski',
    2: 'bliskiego',
    3: 'bliskiemu',
    4: 'bliskim',
    5: 'bliskie',
    6: 'bliska',
    7: 'bliskiej',
    8: 'bliską',
    9: 'bliscy',
    10: 'bliskich',
    11: 'bliskimi',
  },
  {
    1: 'ciężki',
    2: 'ciężkiego',
    3: 'ciężkiemu',
    4: 'ciężkim',
    5: 'ciężkie',
    6: 'ciężka',
    7: 'ciężkiej',
    8: 'ciężką',
    9: 'ciężcy',
    10: 'ciężkich',
    11: 'ciężkimi',
  },
  {
    1: 'lekki',
    2: 'lekkiego',
    3: 'lekkiemu',
    4: 'lekkim',
    5: 'lekkie',
    6: 'lekka',
    7: 'lekkiej',
    8: 'lekką',
    9: 'lekcy',
    10: 'lekkich',
    11: 'lekkimi',
  },
]

export const hard = [
  {
    1: 'bezpieczny',
    2: 'bezpiecznego',
    3: 'bezpiecznemu',
    4: 'bezpiecznym',
    5: 'bezpieczne',
    6: 'bezpieczna',
    7: 'bezpiecznej',
    8: 'bezpieczną',
    9: 'bezpieczni',
    10: 'bezpiecznych',
    11: 'bezpiecznymi',
  },
  {
    1: 'biedny',
    2: 'biednego',
    3: 'biednemu',
    4: 'biednym',
    5: 'biedne',
    6: 'biedna',
    7: 'biednej',
    8: 'biedną',
    9: 'biedni',
    10: 'biednych',
    11: 'biednymi',
  },
  {
    1: 'brązowy',
    2: 'brązowego',
    3: 'brązowemu',
    4: 'brązowym',
    5: 'brązowe',
    6: 'brązowa',
    7: 'brązowej',
    8: 'brązową',
    9: 'brązowi',
    10: 'brązowych',
    11: 'brązowymi',
  },
  {
    1: 'słaby',
    2: 'słabego',
    3: 'słabemu',
    4: 'słabym',
    5: 'słabe',
    6: 'słaba',
    7: 'słabej',
    8: 'słabą',
    9: 'słabi',
    10: 'słabych',
    11: 'słabymi',
  },
  {
    1: 'blady',
    2: 'bladego',
    3: 'blademu',
    4: 'bladym',
    5: 'blade',
    6: 'blada',
    7: 'bladej',
    8: 'bladą',
    9: 'bladzi',
    10: 'bladych',
    11: 'bladymi',
  },
  {
    1: 'młody',
    2: 'młodego',
    3: 'młodemu',
    4: 'młodym',
    5: 'młode',
    6: 'młoda',
    7: 'młodej',
    8: 'młodą',
    9: 'młodzi',
    10: 'młodych',
    11: 'młodymi',
  },
  {
    1: 'twardy',
    2: 'twardego',
    3: 'twardemu',
    4: 'twardym',
    5: 'twarde',
    6: 'twarda',
    7: 'twardej',
    8: 'twardą',
    9: 'twardzi',
    10: 'twardych',
    11: 'twardymi',
  },
  {
    1: 'błahy',
    2: 'błahego',
    3: 'błahemu',
    4: 'błahym',
    5: 'błahe',
    6: 'błaha',
    7: 'błahej',
    8: 'błahą',
    9: 'błazi',
    10: 'błahych',
    11: 'błahymi',
  },
  {
    1: 'cichy',
    2: 'cichego',
    3: 'cichemu',
    4: 'cichym',
    5: 'ciche',
    6: 'cicha',
    7: 'cichej',
    8: 'cichą',
    9: 'cisi',
    10: 'cichych',
    11: 'cichymi',
  },
  {
    1: 'głuchy',
    2: 'głuchego',
    3: 'głuchemu',
    4: 'głuchym',
    5: 'głuche',
    6: 'głucha',
    7: 'głuchej',
    8: 'głuchą',
    9: 'głusi',
    10: 'głuchych',
    11: 'głuchymi',
  },
  {
    1: 'suchy',
    2: 'suchego',
    3: 'suchemu',
    4: 'suchym',
    5: 'suche',
    6: 'sucha',
    7: 'suchej',
    8: 'suchą',
    9: 'susi',
    10: 'suchych',
    11: 'suchymi',
  },
  {
    1: 'biały',
    2: 'białego',
    3: 'białemu',
    4: 'białym',
    5: 'białe',
    6: 'biała',
    7: 'białej',
    8: 'białą',
    9: 'biali',
    10: 'białych',
    11: 'białymi',
  },
  {
    1: 'ciepły',
    2: 'ciepłego',
    3: 'ciepłemu',
    4: 'ciepłym',
    5: 'ciepłe',
    6: 'ciepła',
    7: 'ciepłej',
    8: 'ciepłą',
    9: 'ciepli',
    10: 'ciepłych',
    11: 'ciepłymi',
  },
  {
    1: 'miły',
    2: 'miłego',
    3: 'miłemu',
    4: 'miłym',
    5: 'miłe',
    6: 'miła',
    7: 'miłej',
    8: 'miłą',
    9: 'mili',
    10: 'miłych',
    11: 'miłymi',
  },
  {
    1: 'goły',
    2: 'gołego',
    3: 'gołemu',
    4: 'gołym',
    5: 'gołe',
    6: 'goła',
    7: 'gołej',
    8: 'gołą',
    9: 'goli',
    10: 'gołych',
    11: 'gołymi',
  },
  {
    1: 'wesoły',
    2: 'wesołego',
    3: 'wesołemu',
    4: 'wesołym',
    5: 'wesołe',
    6: 'wesoła',
    7: 'wesołej',
    8: 'wesołą',
    9: 'weseli',
    10: 'wesołych',
    11: 'wesołymi',
  },
  {
    1: 'dorosły',
    2: 'dorosłego',
    3: 'dorosłemu',
    4: 'dorosłym',
    5: 'dorosłe',
    6: 'dorosła',
    7: 'dorosłej',
    8: 'dorosłą',
    9: 'dorośli',
    10: 'dorosłych',
    11: 'dorosłymi',
  },
  {
    1: 'obcisły',
    2: 'obcisłego',
    3: 'obcisłemu',
    4: 'obcisłym',
    5: 'obcisłe',
    6: 'obcisła',
    7: 'obcisłej',
    8: 'obcisłą',
    9: 'obciśli',
    10: 'obcisłych',
    11: 'obcisłymi',
  },
  {
    1: 'niezły',
    2: 'niezłego',
    3: 'niezłemu',
    4: 'niezłym',
    5: 'niezłe',
    6: 'niezła',
    7: 'niezłej',
    8: 'niezłą',
    9: 'nieźli',
    10: 'niezłych',
    11: 'niezłymi',
  },
  {
    1: 'oblazły',
    2: 'oblazłego',
    3: 'oblazłemu',
    4: 'oblazłym',
    5: 'oblazłe',
    6: 'oblazła',
    7: 'oblazłej',
    8: 'oblazłą',
    9: 'oblaźli',
    10: 'oblazłych',
    11: 'oblazłymi',
  },
  {
    1: 'określony',
    2: 'określonego',
    3: 'określonemu',
    4: 'określonym',
    5: 'określone',
    6: 'określona',
    7: 'określonej',
    8: 'określoną',
    9: 'określeni',
    10: 'określonych',
    11: 'określonymi',
  },
  {
    1: 'zadowolony',
    2: 'zadowolonego',
    3: 'zadowolonemu',
    4: 'zadowolonym',
    5: 'zadowolone',
    6: 'zadowolona',
    7: 'zadowolonej',
    8: 'zadowoloną',
    9: 'zadowoleni',
    10: 'zadowolonych',
    11: 'zadowolonymi',
  },
  {
    1: 'zmęczony',
    2: 'zmęczonego',
    3: 'zmęczonemu',
    4: 'zmęczonym',
    5: 'zmęczone',
    6: 'zmęczona',
    7: 'zmęczonej',
    8: 'zmęczoną',
    9: 'zmęczeni',
    10: 'zmęczonych',
    11: 'zmęczonymi',
  },
  {
    1: 'kradziony',
    2: 'kradzionego',
    3: 'kradzionemu',
    4: 'kradzionym',
    5: 'kradzione',
    6: 'kradziona',
    7: 'kradzionej',
    8: 'kradzioną',
    9: 'kradzeni',
    10: 'kradzionych',
    11: 'kradzionymi',
  },
  {
    1: 'spleciony',
    2: 'splecionego',
    3: 'splecionemu',
    4: 'splecionym',
    5: 'splecione',
    6: 'spleciona',
    7: 'splecionej',
    8: 'splecioną',
    9: 'spleceni',
    10: 'splecionych',
    11: 'splecionymi',
  },
  {
    1: 'bolesny',
    2: 'bolesnego',
    3: 'bolesnemu',
    4: 'bolesnym',
    5: 'bolesne',
    6: 'bolesna',
    7: 'bolesnej',
    8: 'bolesną',
    9: 'boleśni',
    10: 'bolesnych',
    11: 'bolesnymi',
  },
  {
    1: 'jasny',
    2: 'jasnego',
    3: 'jasnemu',
    4: 'jasnym',
    5: 'jasne',
    6: 'jasna',
    7: 'jasnej',
    8: 'jasną',
    9: 'jaśni',
    10: 'jasnych',
    11: 'jasnymi',
  },
  {
    1: 'nowoczesny',
    2: 'nowoczesnego',
    3: 'nowoczesnemu',
    4: 'nowoczesnym',
    5: 'nowoczesne',
    6: 'nowoczesna',
    7: 'nowoczesnej',
    8: 'nowoczesną',
    9: 'nowocześni',
    10: 'nowoczesnych',
    11: 'nowoczesnymi',
  },
  {
    1: 'radosny',
    2: 'radosnego',
    3: 'radosnemu',
    4: 'radosnym',
    5: 'radosne',
    6: 'radosna',
    7: 'radosnej',
    8: 'radosną',
    9: 'radośni',
    10: 'radosnych',
    11: 'radosnymi',
  },
  {
    1: 'przyjazny',
    2: 'przyjaznego',
    3: 'przyjaznemu',
    4: 'przyjaznym',
    5: 'przyjazne',
    6: 'przyjazna',
    7: 'przyjaznej',
    8: 'przyjazną',
    9: 'przyjaźni',
    10: 'przyjaznych',
    11: 'przyjaznymi',
  },
  {
    1: 'żelazny',
    2: 'żelaznego',
    3: 'żelaznemu',
    4: 'żelaznym',
    5: 'żelazne',
    6: 'żelazna',
    7: 'żelaznej',
    8: 'żelazną',
    9: 'żelaźni',
    10: 'żelaznych',
    11: 'żelaznymi',
  },
  {
    1: 'bystry',
    2: 'bystrego',
    3: 'bystremu',
    4: 'bystrym',
    5: 'bystre',
    6: 'bystra',
    7: 'bystrej',
    8: 'bystrą',
    9: 'bystrzy',
    10: 'bystrych',
    11: 'bystrymi',
  },
  {
    1: 'chory',
    2: 'chorego',
    3: 'choremu',
    4: 'chorym',
    5: 'chore',
    6: 'chora',
    7: 'chorej',
    8: 'chorą',
    9: 'chorzy',
    10: 'chorych',
    11: 'chorymi',
  },
  {
    1: 'dobry',
    2: 'dobrego',
    3: 'dobremu',
    4: 'dobrym',
    5: 'dobre',
    6: 'dobra',
    7: 'dobrej',
    8: 'dobrą',
    9: 'dobrzy',
    10: 'dobrych',
    11: 'dobrymi',
  },
  {
    1: 'mądry',
    2: 'mądrego',
    3: 'mądremu',
    4: 'mądrym',
    5: 'mądre',
    6: 'mądra',
    7: 'mądrej',
    8: 'mądrą',
    9: 'mądrzy',
    10: 'mądrych',
    11: 'mądrymi',
  },
  {
    1: 'szczery',
    2: 'szczerego',
    3: 'szczeremu',
    4: 'szczerym',
    5: 'szczere',
    6: 'szczera',
    7: 'szczerej',
    8: 'szczerą',
    9: 'szczerzy',
    10: 'szczerych',
    11: 'szczerymi',
  },
  {
    1: 'bogaty',
    2: 'bogatego',
    3: 'bogatemu',
    4: 'bogatym',
    5: 'bogate',
    6: 'bogata',
    7: 'bogatej',
    8: 'bogatą',
    9: 'bogaci',
    10: 'bogatych',
    11: 'bogatymi',
  },
  {
    1: 'otwarty',
    2: 'otwartego',
    3: 'otwartemu',
    4: 'otwartym',
    5: 'otwarte',
    6: 'otwarta',
    7: 'otwartej',
    8: 'otwartą',
    9: 'otwarci',
    10: 'otwartych',
    11: 'otwartymi',
  },
  {
    1: 'pracowity',
    2: 'pracowitego',
    3: 'pracowitemu',
    4: 'pracowitym',
    5: 'pracowite',
    6: 'pracowita',
    7: 'pracowitej',
    8: 'pracowitą',
    9: 'pracowici',
    10: 'pracowitych',
    11: 'pracowitymi',
  },
  {
    1: 'skryty',
    2: 'skrytego',
    3: 'skrytemu',
    4: 'skrytym',
    5: 'skryte',
    6: 'skryta',
    7: 'skrytej',
    8: 'skrytą',
    9: 'skryci',
    10: 'skrytych',
    11: 'skrytymi',
  },
  {
    1: 'czysty',
    2: 'czystego',
    3: 'czystemu',
    4: 'czystym',
    5: 'czyste',
    6: 'czysta',
    7: 'czystej',
    8: 'czystą',
    9: 'czyści',
    10: 'czystych',
    11: 'czystymi',
  },
  {
    1: 'gęsty',
    2: 'gęstego',
    3: 'gęstemu',
    4: 'gęstym',
    5: 'gęste',
    6: 'gęsta',
    7: 'gęstej',
    8: 'gęstą',
    9: 'gęści',
    10: 'gęstych',
    11: 'gęstymi',
  },
  {
    1: 'prosty',
    2: 'prostego',
    3: 'prostemu',
    4: 'prostym',
    5: 'proste',
    6: 'prosta',
    7: 'prostej',
    8: 'prostą',
    9: 'prości',
    10: 'prostych',
    11: 'prostymi',
  },
  {
    1: 'pusty',
    2: 'pustego',
    3: 'pustemu',
    4: 'pustym',
    5: 'puste',
    6: 'pusta',
    7: 'pustej',
    8: 'pustą',
    9: 'puści',
    10: 'pustych',
    11: 'pustymi',
  },
]
